Patch 1
symcon/AnwesenheitsSimulation pull request #24
Opened 2020-08-03 23:21 UTC by KingKahn123

I have added a new variable which indicates when the next light must be switched on or off. As I still have the problem that in some cases the internal timer gets inactive, I would use this "NextTrigger" variable as a WatchDog.

2021-01-07 14:33 UTC, paresy requested changes
Hi! And sorry for taking so long to review this. I just haven't seem it in my list. 

Then change looks good and small and i'd love to merge it. Just a few points:
a) I'd prefer to use an Integer Variable with the UnixTimestampDate profile (This also solves the issue, that you did not translate 'Keiner')
b) We need all checks to be "green" :)

2021-01-08 09:33 UTC, KingKahn123 commented
Hi, now I have changed it and everything is green. Is it ok with you?

2021-01-08 11:43 UTC, paresy requested changes
I added two comment. Could you have a look?

2021-01-08 11:43 UTC, paresy commented on AnwesenheitsSimulation/module.php
> +        $this->RegisterVariableInteger('NextTrigger', $this->Translate('Next Trigger'), '');
The last parameter (profile) should be ~UnixTimestamp. (See here: https://www.symcon.de/en/service/documentation/components/visualizations/object-presentation/datetime/)

2021-01-08 11:43 UTC, paresy commented on AnwesenheitsSimulation/module.php
> +            $this->SetValue('NextTrigger', ($NextSimulationData['nextSwitchTimestamp'] - $this->getTime() + 1) * 1000);
I think this should be $NextSimulationData['nextSwitchTimestamp'] only. Can you verify this? (Your current code shouldn't work properly!?)

2021-01-08 11:44 UTC, paresy commented
@TillBrede: Sobald er die Änderungen eingebaut hat - magst du das mal auschecken und Funktional überprüfen? :-)

2021-06-07 07:12 UTC, paresy commented
I will close this for now. Please reopen, if you would like to pick up adding the required changes :-)

2021-06-07 07:12 UTC, closed without merging