Use new SelectVariable parameters
symcon/AnwesenheitsSimulation pull request #27
Opened 2021-08-20 08:51 UTC by TillBrede

* Added status column
* Fixed legacy tests
* updated and added tests
Fixes symcon/modules#186

2021-09-06 12:56 UTC, DrNiels requested changes

2021-09-06 12:56 UTC, DrNiels commented on AnwesenheitsSimulation/form.json
> +			"columns": [{
Da sind Tabs, keine Spaces!

2021-09-06 12:56 UTC, DrNiels commented on AnwesenheitsSimulation/locale.json
> +			"Doesn't Exist": "Existiert  nicht"
Bei "Existiert nicht" sind zwei Leerzeichen, also eins zu viel

2021-09-06 12:56 UTC, DrNiels commented on AnwesenheitsSimulation/form.json
> +          "width": "150px"
Jede Spalte benötigt einen add-Wert für das Hinzufügen eines neuen Eintrags, daher können keine neuen Werte hinzugefügt werden!

2021-11-12 19:51 UTC, paresy commented
@TillBrede Magst du dies noch einmal aktualisieren?

Außerdem kann man keine Elemente hinzufügen, da die Konsole meckert, dass die Status Spalte keinen "add" Wert hat.

2021-11-12 19:51 UTC, paresy requested changes
@TillBrede Magst du dies noch einmal aktualisieren?

Außerdem kann man keine Elemente hinzufügen, da die Konsole meckert, dass die Status Spalte keinen "add" Wert hat.

2022-04-04 10:07 UTC, DrNiels requested changes

2022-04-04 10:07 UTC, DrNiels commented on AnwesenheitsSimulation/form.json
> +          "add": ""
Die Einrückung von Status ist verkehrt, das sollte auf einer Ebene mit den anderen Spalten stehen

2022-06-10 08:31 UTC, DrNiels requested changes
Du müsstest noch die Kompatibilität auf 6.0 anheben, da die neuen Parameter für SelectVariable erst ab dann nutzbar sind.

2022-06-29 10:58 UTC, DrNiels approved these changes

2022-06-29 10:59 UTC, paresy approved these changes

2022-06-29 10:59 UTC, DrNiels requested changes
Mach Konflikte weg!

2022-06-29 11:00 UTC, merged